
# This is the Website title, which appears in the top of every page.
title: PortaWiki Demo

# Set the home page, this page is loaded if no specific path is given.
home: Home.md

# Choose a theme, which will correspond to a folder in the themes/ folder. This folder should contain css files such as colors.css and layout.css
theme: woodland

# Where should the index page look for "Home.md", "sidenav.md" and all the other pages?
contentpath: 'ACGWebSite/content/'

# The logo should be a small snippet of html that is loaded into the top left corner of the page
navigation_logo: assets/logo.html

# This is the navigation sidebar
navigation_sidebar: assets/sidenav.md

# This is the navigation that is part of the horizontal header bar.
navigation_topbar: assets/headernav.md

# Developer stuff
show_config: true
extension_precedence: ["md", "html", "htm", "txt"]
extension_types: ["markdown", "html", "html", "text"]

# This is the search tool, which is an html page behind the "search" link
# It hasnt been developed yet!
search: Search.html

# This is the user config and other toos page, which is an html page behind the "hamburger" link
# It hasnt been developed yet!
settings: Settings.html

# Search index items
search_fields: ["title", "description", "keywords", "body"]
search_exclude: ["ACGWebSite/content/assets", "Search.html"]
search+max_preview_chars: 275
search_index: "src/lunr_index.js"
